#!/bin/bash

submodule_path="SwiftLint"

get_latest_tag() {
    cd "$submodule_path" || exit

    git fetch --tags
    latest_tag=$(git describe --tags $(git rev-list --tags --max-count=1))
    echo "$latest_tag"
}

check_version() {
    latest_tag=$(get_latest_tag)
    if [ -z "$latest_tag" ]; then
        echo "Failed to fetch latest tag. Exiting..."
        exit 1
    fi

    current_tag=$(git -C "$submodule_path" describe --tags)
    if [ "$current_tag" = "$latest_tag" ]; then
        echo "No updates available."
    else
        echo "New version available: $latest_tag"

        git -C "$submodule_path" checkout "$latest_tag"

        git checkout -b "release/$latest_tag"
        git add -u

        git commit -m "update $submodule_path version to $latest_tag"
        git push origin HEAD
    fi
}

check_version