#!/bin/bash

submodule_url="https://github.com/yonaskolb/XcodeGen"
submodule_path="XcodeGen"

get_latest_tag() {
    git clone "$submodule_url" "$submodule_path"
    cd "$submodule_path" || exit

    git fetch --tags
    latest_tag=$(git describe --tags $(git rev-list --tags --max-count=1))
    echo "$latest_tag"
}

check_version() {
    latest_tag=$(get_latest_tag)
    if [ -z "$latest_tag" ]; then
        echo "Failed to fetch latest tag. Exiting..."
        exit 1
    fi

    current_tag=$(cat version)
    if [ "$current_tag" = "$latest_tag" ]; then
        echo "No updates available."
    else
        echo "New version available: $latest_tag"

        echo "$latest_tag" > version

        git checkout -b "release/$latest_tag"
        git add -u

        git commit -m "update $submodule_path version to $latest_tag"
        git push origin HEAD
    fi
}

check_version
