name: test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          # renovate: datasource=github-runners
          - os: macos-26
            xcode: "/Applications/Xcode_26.3.app"
          - os: ubuntu-latest
            # renovate: datasource=docker
            container: swift:6.3
    runs-on: ${{ matrix.os }}
    container:
      image: ${{ matrix.container }}
    steps:
      - uses: actions/checkout@v6
      - name: Clone XcodeGen
        run: |
          bash clone-version
      - uses: actions/cache@v5
        with:
          path: XcodeGen/.build
          key: ${{ runner.os }}-xcodegen-${{ hashFiles('XcodeGen/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-xcodegen-${{ hashFiles('XcodeGen/Package.resolved') }}
            ${{ runner.os }}-xcodegen
      - name: Select Xcode
        if: matrix.xcode != null
        run: sudo xcode-select --switch "${{ matrix.xcode }}"
      - name: Swift version
        run: swift --version
      - name: Make project
        run: cd XcodeGen && swift build
